modLoader = "kotlinforforge"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "cobbleblackout"
version = "${version}"
displayName = "Cobblemon Blackout"
authors = "Sylvonir"
description = '''
Players blackout and get sent to their spawnpoint if all of their Pokemon are knocked out in the wild.
'''
#logoFile = ""

[[dependencies.cobbleblackout]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbleblackout]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbleblackout]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbleblackout]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[4.3,)"
ordering = "AFTER"
side = "BOTH"